---
abstract: "Perl module for accessing Sailthru's platform"
author:
  - 'Sam Gerstenzang <sgerstenzang@stanford.edu>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120530'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Triggermail
no_index:
  directory:
    - t
    - inc
requires:
  Digest::MD5: 0
  HTTP::Request: 0
  JSON::XS: 0
  LWP: 0
  LWP::Protocol::https: 0
  Params::Validate: 0
  URI::Escape: 0
version: 1.005
